apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: aidemo
spec:
  selector:
    matchLabels:
      app: aidemo
  replicas: 1 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: aidemo
    spec:
      containers:
        - name: aidemo
          image: aidemo:latest # Image that will be used inside the container in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster